title: 邸志雄个人主页
email: zxdi@home.swjtu.edu.cn
description: >-
  邸志雄，博士，硕士研究生导师，西南交通大学信息学院电子工程系副系主任。CCF会员、
  中国图象图形学学会军民融合专委会成员、新工科联盟“可定制计算”专委会成员。研究
  方向为高性能图像编解码芯片技术研究、布局布线算法研究。近年来主持国家自然科学
  基金青年项目、四川省科技厅项高新重点项目等项目，参与完成了我国自主研制的首颗
  宇航级高速图像压缩芯片“雅芯-天图”。指导学生多次获得创芯大赛、全国大学生集成电
  路创新创业大赛、集成电路设计EDA精英挑战赛、全国大学生FPGA创新设计竞赛、Xilinx
  OpenHW等国家级奖项。
theme: jekyll-theme-cayman
encoding: utf-8
